server:
  port: 9001

spring:
  dataSource:
    url: jdbc:mysql://localhost:3306/toy_db
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: org.owenqing.springboot.x.entity
  configuration:
    map-underscore-to-camel-case: true

foo-kafka:
  servers:
    - 172.18.96.231:9092
  group_id: foo_consumer